### ISSUE TITLE
Roadmap - Parametrizar la configuración

### ISSUE THREAD

**Issue by joshuamzm** [pa-w/aquinecesitamos#1]
Hola, quisiera poder ayudar con tu proyecto. ¿Cómo puedo apoyarte o que tienes en mente con la parte de parametrización o algún otro punto del Roadmap?

Una recomendación por lo pronto es agregar un `package.json` con `npm init` para poder instalar de forma local los paquetes de los que dependes.

**Comment by pa-w** [comment]
Hola! Creo que estaría bien poder señalar dónde está el archivo con la configuración para la autenticación de google drive, mover la configuración de los textos y otras variables específicas al use case a un archivo aparte y/o hacer el script un módulo para npm.

**Comment by joshuamzm** [comment]
En #4 parametricé el ID del GDoc y la localización del archivo con el API key. Para los demás valores creo que valdría más la pena definir otro JSON config con esas variables y llamarlo desde el script.
