### ISSUE TITLE
Roadmap - Hacer el script un módulo para npm

### ISSUE THREAD

**Issue by pa-w** [pa-w/aquinecesitamos#2]
Estaría bueno poder reutilizar al máximo este script y, para ello, qué mejor que adaptarlo para ser un modulito?

**Comment by joshuamzm** [comment]
Con #4 se puede publicar a NPM el módulo pero faltaría darle una estructura para exportar la función del módulo. Algo así como `module.exports = generateImages` o algo parecido.
