### ISSUE TITLE
Deploy - Container?

### ISSUE THREAD

**Issue by pa-w** [pa-w/aquinecesitamos#3]
Cómo hacer que sea fácil el deploy? Para empezar a producir y obtener imágenes rápido.

**Comment by joshuamzm** [comment]
Estuve intentando crear una imagen de Docker con GD y Node instalados y las herramientas para compilar lo necesario para usar 'node-gd' pero se hizo muy grande la imagen de docker (centenas de megas).

Otro problema que encontré es que el script genera la imagen en un directorio output, habría que mapear este directorio con un volumen local.

Tal vez convendría más levantar un mini servicio web con Express o Koa para habilitar un endpoint que sirva la imagen.
